### ISSUE TITLE
Miss

### ISSUE THREAD

**Issue by antoinedumez** [gpetraroli/server_environment_configs#1]
Hey there Thanks a lot for the works !! 

- There is litle mistake here, nothing write as you can see :

![image](https://github.com/gpetraroli/server_environment_configs/assets/95721687/c8a0f6a5-f1ff-4e8e-b773-d97db29349db)

- Here I think you meant php-8.2, think it is the wrong version : 
![image](https://github.com/gpetraroli/server_environment_configs/assets/95721687/4c141eea-5dde-4246-9357-a14947c3ebf5)

**Comment by gpetraroli** [comment]
Thank you @antoinedumez, you are right! Consider making a PR.

**Comment by gpetraroli** [comment]
Fixed with PR https://github.com/gpetraroli/server_environment_configs/pull/2
